import React from 'react'
import type { Metadata } from 'next'
import { ThemeProvider } from 'next-themes'
import { Martian_Mono as Font } from 'next/font/google'
import '../styles/globals.css'
import clsx from 'clsx'

export const metadata: Metadata = {
  title: 'Hit Dice App',
  description: 'Generated by create next app',
}

const font = Font({
  weight: ['300', '400', '500'],
  subsets: ['latin'],
  fallback: [
    'ui-monospace',
    'Cascadia Code',
    'Source Code Pro',
    'Menlo',
    'Consolas',
    'DejaVu Sans Mono',
    'monospace',
  ],
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={clsx(font.className, 'antialiased')}
    >
      <body>
        <ThemeProvider>{children}</ThemeProvider>
      </body>
    </html>
  )
}
