import { Monster } from '@/app/api/monsters/types'

const monsters: Monster[] = [
  { name: 'Aboleth', hitDice: '18d10+36' },
  { name: 'Acolyte', hitDice: '2d8' },
  { name: 'Adult Black Dragon', hitDice: '17d12+85' },
  { name: 'Adult Blue Dragon', hitDice: '18d12+108' },
  { name: 'Adult Brass Dragon', hitDice: '15d12+75' },
  { name: 'Adult Bronze Dragon', hitDice: '17d12+102' },
  { name: 'Adult Copper Dragon', hitDice: '16d12+80' },
  { name: 'Adult Gold Dragon', hitDice: '19d12+133' },
  { name: 'Adult Green Dragon', hitDice: '18d12+90' },
  { name: 'Adult Red Dragon', hitDice: '19d12+133' },
  { name: 'Adult Silver Dragon', hitDice: '18d12+126' },
  { name: 'Adult White Dragon', hitDice: '16d12+96' },
  { name: 'Air Elemental', hitDice: '12d10+24' },
  { name: 'Ancient Black Dragon', hitDice: '21d20+147' },
  { name: 'Ancient Blue Dragon', hitDice: '26d20+208' },
  { name: 'Ancient Brass Dragon', hitDice: '17d20+119' },
  { name: 'Ancient Bronze Dragon', hitDice: '24d20+192' },
  { name: 'Ancient Copper Dragon', hitDice: '20d20+140' },
  { name: 'Ancient Gold Dragon', hitDice: '28d20+252' },
  { name: 'Ancient Green Dragon', hitDice: '22d20+154' },
  { name: 'Ancient Red Dragon', hitDice: '28d20+252' },
  { name: 'Ancient Silver Dragon', hitDice: '25d20+225' },
  { name: 'Ancient White Dragon', hitDice: '18d20+144' },
  { name: 'Androsphinx', hitDice: '19d10+95' },
  { name: 'Animated Armor', hitDice: '6d8+6' },
  { name: 'Ankheg', hitDice: '6d10+6' },
  { name: 'Ape', hitDice: '3d8+6' },
  { name: 'Archmage', hitDice: '18d8+18' },
  { name: 'Assassin', hitDice: '12d8+24' },
  { name: 'Awakened Shrub', hitDice: '3d6' },
  { name: 'Awakened Tree', hitDice: '7d12+14' },
  { name: 'Axe Beak', hitDice: '3d10+3' },
  { name: 'Azer', hitDice: '6d8+12' },
  { name: 'Baboon', hitDice: '1d6' },
  { name: 'Badger', hitDice: '1d4+1' },
  { name: 'Balor', hitDice: '21d12+126' },
  { name: 'Bandit', hitDice: '2d8+2' },
  { name: 'Bandit Captain', hitDice: '10d8+20' },
  { name: 'Barbed Devil', hitDice: '13d8+52' },
  { name: 'Basilisk', hitDice: '8d8+16' },
  { name: 'Bat', hitDice: '1d4-1' },
  { name: 'Bearded Devil', hitDice: '8d8+16' },
  { name: 'Behir', hitDice: '16d12+64' },
  { name: 'Berserker', hitDice: '9d8+27' },
  { name: 'Black Bear', hitDice: '3d8+6' },
  { name: 'Black Dragon Wyrmling', hitDice: '6d8+6' },
  { name: 'Black Pudding', hitDice: '10d10+30' },
  { name: 'Blink Dog', hitDice: '4d8+4' },
  { name: 'Blood Hawk', hitDice: '2d6' },
  { name: 'Blue Dragon Wyrmling', hitDice: '8d8+16' },
  { name: 'Boar', hitDice: '2d8+2' },
  { name: 'Bone Devil', hitDice: '15d10+60' },
  { name: 'Brass Dragon Wyrmling', hitDice: '3d8+3' },
  { name: 'Bronze Dragon Wyrmling', hitDice: '5d8+10' },
  { name: 'Brown Bear', hitDice: '4d10+12' },
  { name: 'Bugbear', hitDice: '5d8+5' },
  { name: 'Bulette', hitDice: '9d10+45' },
  { name: 'Camel', hitDice: '2d10+4' },
  { name: 'Cat', hitDice: '1d4' },
  { name: 'Centaur', hitDice: '6d10+12' },
  { name: 'Chain Devil', hitDice: '10d8+40' },
  { name: 'Chimera', hitDice: '12d10+48' },
  { name: 'Chuul', hitDice: '11d10+33' },
  { name: 'Clay Golem', hitDice: '14d10+56' },
  { name: 'Cloaker', hitDice: '12d10+12' },
  { name: 'Cloud Giant', hitDice: '16d12+96' },
  { name: 'Cockatrice', hitDice: '6d6+6' },
  { name: 'Commoner', hitDice: '1d8' },
  { name: 'Constrictor Snake', hitDice: '2d10+2' },
  { name: 'Copper Dragon Wyrmling', hitDice: '4d8+4' },
  { name: 'Couatl', hitDice: '13d8+39' },
  { name: 'Crab', hitDice: '1d4' },
  { name: 'Crocodile', hitDice: '3d10+3' },
  { name: 'Cult Fanatic', hitDice: '6d8+6' },
  { name: 'Cultist', hitDice: '2d8' },
  { name: 'Darkmantle', hitDice: '5d6+5' },
  { name: 'Death Dog', hitDice: '6d8+12' },
  { name: 'Deep Gnome (Svirfneblin)', hitDice: '3d6+6' },
  { name: 'Deer', hitDice: '1d8' },
  { name: 'Deva', hitDice: '16d8+64' },
  { name: 'Dire Wolf', hitDice: '5d10+10' },
  { name: 'Djinni', hitDice: '14d10+84' },
  { name: 'Doppelganger', hitDice: '8d8+16' },
  { name: 'Draft Horse', hitDice: '3d10+3' },
  { name: 'Dragon Turtle', hitDice: '22d20+110' },
  { name: 'Dretch', hitDice: '4d6+4' },
  { name: 'Drider', hitDice: '13d10+52' },
  { name: 'Drow', hitDice: '3d8' },
  { name: 'Druid', hitDice: '5d8+5' },
  { name: 'Dryad', hitDice: '5d8' },
  { name: 'Duergar', hitDice: '4d8+8' },
  { name: 'Dust Mephit', hitDice: '5d6' },
  { name: 'Eagle', hitDice: '1d6' },
  { name: 'Earth Elemental', hitDice: '12d10+60' },
  { name: 'Efreeti', hitDice: '16d10+112' },
  { name: 'Elephant', hitDice: '8d12+24' },
  { name: 'Elk', hitDice: '2d10+2' },
  { name: 'Erinyes', hitDice: '18d8+72' },
  { name: 'Ettercap', hitDice: '8d8+8' },
  { name: 'Ettin', hitDice: '10d10+30' },
  { name: 'Fire Elemental', hitDice: '12d10+36' },
  { name: 'Fire Giant', hitDice: '13d12+78' },
  { name: 'Flesh Golem', hitDice: '11d8+44' },
  { name: 'Flying Snake', hitDice: '2d4' },
  { name: 'Flying Sword', hitDice: '5d6' },
  { name: 'Frog', hitDice: '1d4-1' },
  { name: 'Frost Giant', hitDice: '12d12+60' },
  { name: 'Gargoyle', hitDice: '7d8+21' },
  { name: 'Gelatinous Cube', hitDice: '8d10+40' },
  { name: 'Ghast', hitDice: '8d8' },
  { name: 'Ghost', hitDice: '10d8' },
  { name: 'Ghoul', hitDice: '5d8' },
  { name: 'Giant Ape', hitDice: '15d12+60' },
  { name: 'Giant Badger', hitDice: '2d8+4' },
  { name: 'Giant Bat', hitDice: '4d10' },
  { name: 'Giant Boar', hitDice: '5d10+15' },
  { name: 'Giant Centipede', hitDice: '1d6+1' },
  { name: 'Giant Constrictor Snake', hitDice: '8d12+8' },
  { name: 'Giant Crab', hitDice: '3d8' },
  { name: 'Giant Crocodile', hitDice: '9d12+27' },
  { name: 'Giant Eagle', hitDice: '4d10+4' },
  { name: 'Giant Elk', hitDice: '5d12+10' },
  { name: 'Giant Fire Beetle', hitDice: '1d6+1' },
  { name: 'Giant Frog', hitDice: '4d8' },
  { name: 'Giant Goat', hitDice: '3d10+3' },
  { name: 'Giant Hyena', hitDice: '6d10+12' },
  { name: 'Giant Lizard', hitDice: '3d10+3' },
  { name: 'Giant Octopus', hitDice: '8d10+8' },
  { name: 'Giant Owl', hitDice: '3d10+3' },
  { name: 'Giant Poisonous Snake', hitDice: '2d8+2' },
  { name: 'Giant Rat', hitDice: '2d6' },
  { name: 'Giant Rat (Diseased)', hitDice: '2d6' },
  { name: 'Giant Scorpion', hitDice: '7d10+14' },
  { name: 'Giant Sea Horse', hitDice: '3d10' },
  { name: 'Giant Shark', hitDice: '11d12+55' },
  { name: 'Giant Spider', hitDice: '4d10+4' },
  { name: 'Giant Toad', hitDice: '6d10+6' },
  { name: 'Giant Vulture', hitDice: '3d10+6' },
  { name: 'Giant Wasp', hitDice: '3d8' },
  { name: 'Giant Weasel', hitDice: '2d8' },
  { name: 'Giant Wolf Spider', hitDice: '2d8+2' },
  { name: 'Gibbering Mouther', hitDice: '9d8+27' },
  { name: 'Glabrezu', hitDice: '15d10+75' },
  { name: 'Gladiator', hitDice: '15d8+45' },
  { name: 'Gnoll', hitDice: '5d8' },
  { name: 'Goat', hitDice: '1d8' },
  { name: 'Goblin', hitDice: '2d6' },
  { name: 'Gold Dragon Wyrmling', hitDice: '8d8+24' },
  { name: 'Gorgon', hitDice: '12d10+48' },
  { name: 'neutral Ooze', hitDice: '3d8+9' },
  { name: 'Green Dragon Wyrmling', hitDice: '7d8+7' },
  { name: 'Green Hag', hitDice: '11d8+33' },
  { name: 'Grick', hitDice: '6d8' },
  { name: 'Griffon', hitDice: '7d10+21' },
  { name: 'Grimlock', hitDice: '2d8+2' },
  { name: 'Guard', hitDice: '2d8+2' },
  { name: 'Guardian Naga', hitDice: '15d10+45' },
  { name: 'Gynosphinx', hitDice: '16d10+48' },
  { name: 'Half-Red Dragon Veteran', hitDice: '10d8+20' },
  { name: 'Harpy', hitDice: '7d8+7' },
  { name: 'Hawk', hitDice: '1d4-1' },
  { name: 'Hell Hound', hitDice: '7d8+14' },
  { name: 'Hezrou', hitDice: '13d10+65' },
  { name: 'Hill Giant', hitDice: '10d12+40' },
  { name: 'Hippogriff', hitDice: '3d10+3' },
  { name: 'Hobgoblin', hitDice: '2d8+2' },
  { name: 'Homunculus', hitDice: '2d4' },
  { name: 'Horned Devil', hitDice: '17d10+85' },
  { name: 'Hunter Shark', hitDice: '6d10+12' },
  { name: 'Hydra', hitDice: '15d12+75' },
  { name: 'Hyena', hitDice: '1d8+1' },
  { name: 'Ice Devil', hitDice: '19d10+76' },
  { name: 'Ice Mephit', hitDice: '6d6' },
  { name: 'Imp', hitDice: '3d4+3' },
  { name: 'Invisible Stalker', hitDice: '16d8+32' },
  { name: 'Iron Golem', hitDice: '20d10+100' },
  { name: 'Jackal', hitDice: '1d6' },
  { name: 'Killer Whale', hitDice: '12d12+12' },
  { name: 'Knight', hitDice: '8d8+16' },
  { name: 'Kobold', hitDice: '2d6-2' },
  { name: 'Kraken', hitDice: '27d20+189' },
  { name: 'Lamia', hitDice: '13d10+26' },
  { name: 'Lemure', hitDice: '3d8' },
  { name: 'Lich', hitDice: '18d8+54' },
  { name: 'Lion', hitDice: '4d10+4' },
  { name: 'Lizard', hitDice: '1d4' },
  { name: 'Lizardfolk', hitDice: '4d8+4' },
  { name: 'Mage', hitDice: '9d8' },
  { name: 'Magma Mephit', hitDice: '5d6+5' },
  { name: 'Magmin', hitDice: '2d6+2' },
  { name: 'Mammoth', hitDice: '11d12+55' },
  { name: 'Manticore', hitDice: '8d10+24' },
  { name: 'Marilith', hitDice: '18d10+90' },
  { name: 'Mastiff', hitDice: '1d8+1' },
  { name: 'Medusa', hitDice: '17d8+51' },
  { name: 'Merfolk', hitDice: '2d8+2' },
  { name: 'Merrow', hitDice: '6d10+12' },
  { name: 'Mimic', hitDice: '9d8+18' },
  { name: 'Minotaur', hitDice: '9d10+27' },
  { name: 'Minotaur Skeleton', hitDice: '9d10+18' },
  { name: 'Mule', hitDice: '2d8+2' },
  { name: 'Mummy', hitDice: '9d8+18' },
  { name: 'Mummy Lord', hitDice: '13d8+39' },
  { name: 'Nalfeshnee', hitDice: '16d10+96' },
  { name: 'Night Hag', hitDice: '15d8+45' },
  { name: 'Nightmare', hitDice: '8d10+24' },
  { name: 'Noble', hitDice: '2d8' },
  { name: 'Ochre Jelly', hitDice: '6d10+12' },
  { name: 'Octopus', hitDice: '1d6' },
  { name: 'Ogre', hitDice: '7d10+21' },
  { name: 'Ogre Zombie', hitDice: '9d10+36' },
  { name: 'Oni', hitDice: '13d10+39' },
  { name: 'Orc', hitDice: '2d8+6' },
  { name: 'Otyugh', hitDice: '12d10+48' },
  { name: 'Owl', hitDice: '1d4-1' },
  { name: 'Owlbear', hitDice: '7d10+21' },
  { name: 'Panther', hitDice: '3d8' },
  { name: 'Pegasus', hitDice: '7d10+21' },
  { name: 'Phase Spider', hitDice: '5d10+5' },
  { name: 'Pit Fiend', hitDice: '24d10+168' },
  { name: 'Planetar', hitDice: '16d10+112' },
  { name: 'Plesiosaurus', hitDice: '8d10+24' },
  { name: 'Poisonous Snake', hitDice: '1d4' },
  { name: 'Polar Bear', hitDice: '5d10+15' },
  { name: 'Pony', hitDice: '2d8+2' },
  { name: 'Priest', hitDice: '5d8+5' },
  { name: 'Pseudodragon', hitDice: '2d4+2' },
  { name: 'Purple Worm', hitDice: '15d20+90' },
  { name: 'Quasit', hitDice: '3d4' },
  { name: 'Quipper', hitDice: '1d4-1' },
  { name: 'Rakshasa', hitDice: '13d8+52' },
  { name: 'Rat', hitDice: '1d4-1' },
  { name: 'Raven', hitDice: '1d4-1' },
  { name: 'Red Dragon Wyrmling', hitDice: '10d8+30' },
  { name: 'Reef Shark', hitDice: '4d8+1' },
  { name: 'Remorhaz', hitDice: '17d12+85' },
  { name: 'Rhinoceros', hitDice: '6d10+12' },
  { name: 'Riding Horse', hitDice: '2d10+2' },
  { name: 'Roc', hitDice: '16d20+80' },
  { name: 'Roper', hitDice: '11d10+33' },
  { name: 'Rug of Smothering', hitDice: '6d10' },
  { name: 'Rust Monster', hitDice: '5d8+5' },
  { name: 'Saber-Toothed Tiger', hitDice: '7d10+14' },
  { name: 'Sahuagin', hitDice: '4d8+4' },
  { name: 'Salamander', hitDice: '12d10+24' },
  { name: 'Satyr', hitDice: '7d8' },
  { name: 'Scorpion', hitDice: '1d4-1' },
  { name: 'Scout', hitDice: '3d8+3' },
  { name: 'Sea Hag', hitDice: '7d8+21' },
  { name: 'Sea Horse', hitDice: '1d4-1' },
  { name: 'Shadow', hitDice: '3d8+3' },
  { name: 'Shambling Mound', hitDice: '16d10+48' },
  { name: 'Shield Guardian', hitDice: '15d10+60' },
  { name: 'Shrieker', hitDice: '3d8' },
  { name: 'Silver Dragon Wyrmling', hitDice: '6d8+18' },
  { name: 'Skeleton', hitDice: '2d8+4' },
  { name: 'Solar', hitDice: '18d10+144' },
  { name: 'Specter', hitDice: '5d8' },
  { name: 'Spider', hitDice: '1d4-1' },
  { name: 'Spirit Naga', hitDice: '10d10+20' },
  { name: 'Sprite', hitDice: '1d4' },
  { name: 'Spy', hitDice: '6d8' },
  { name: 'Steam Mephit', hitDice: '6d6' },
  { name: 'Stirge', hitDice: '1d4' },
  { name: 'Stone Giant', hitDice: '11d12+55' },
  { name: 'Stone Golem', hitDice: '17d10+85' },
  { name: 'Storm Giant', hitDice: '20d12+100' },
  { name: 'Succubus/Incubus', hitDice: '12d8+12' },
  { name: 'Swarm of Bats', hitDice: '5d8' },
  { name: 'Swarm of Beetles', hitDice: '5d8' },
  { name: 'Swarm of Centipedes', hitDice: '5d8' },
  { name: 'Swarm of Insects', hitDice: '5d8' },
  { name: 'Swarm of Poisonous Snakes', hitDice: '8d8' },
  { name: 'Swarm of Quippers', hitDice: '8d8-8' },
  { name: 'Swarm of Rats', hitDice: '7d8-7' },
  { name: 'Swarm of Ravens', hitDice: '7d8-7' },
  { name: 'Swarm of Spiders', hitDice: '5d8' },
  { name: 'Swarm of Wasps', hitDice: '5d8' },
  { name: 'Tarrasque', hitDice: '33d20+330' },
  { name: 'Thug', hitDice: '5d8+10' },
  { name: 'Tiger', hitDice: '5d10+10' },
  { name: 'Treant', hitDice: '12d12+60' },
  { name: 'Tribal Warrior', hitDice: '2d8+2' },
  { name: 'Triceratops', hitDice: '10d12+30' },
  { name: 'Troll', hitDice: '8d10+40' },
  { name: 'Tyrannosaurus Rex', hitDice: '13d12+52' },
  { name: 'Unicorn', hitDice: '9d10+18' },
  { name: 'Vampire', hitDice: '17d8+68' },
  { name: 'Vampire Spawn', hitDice: '11d8+33' },
  { name: 'Veteran', hitDice: '9d8+18' },
  { name: 'Violet Fungus', hitDice: '4d8' },
  { name: 'Vrock', hitDice: '11d10+44' },
  { name: 'Vulture', hitDice: '1d8+1' },
  { name: 'Warhorse', hitDice: '3d10+3' },
  { name: 'Warhorse Skeleton', hitDice: '3d10+6' },
  { name: 'Water Elemental', hitDice: '12d10+48' },
  { name: 'Weasel', hitDice: '1d4-1' },
  { name: 'Werebear', hitDice: '18d8+54' },
  { name: 'Wereboar', hitDice: '12d8+24' },
  { name: 'Wererat', hitDice: '6d8+6' },
  { name: 'Weretiger', hitDice: '16d8+48' },
  { name: 'Werewolf', hitDice: '9d8+18' },
  { name: 'White Dragon Wyrmling', hitDice: '5d8+10' },
  { name: 'Wight', hitDice: '6d8+18' },
  { name: "Will-o'-Wisp", hitDice: '9d4' },
  { name: 'Winter Wolf', hitDice: '10d10+20' },
  { name: 'Wolf', hitDice: '2d8+2' },
  { name: 'Worg', hitDice: '4d10+4' },
  { name: 'Wraith', hitDice: '9d8+27' },
  { name: 'Wyvern', hitDice: '13d10+39' },
  { name: 'Xorn', hitDice: '7d8+42' },
  { name: 'Young Black Dragon', hitDice: '15d10+45' },
  { name: 'Young Blue Dragon', hitDice: '16d10+64' },
  { name: 'Young Brass Dragon', hitDice: '13d10+39' },
  { name: 'Young Bronze Dragon', hitDice: '15d10+60' },
  { name: 'Young Copper Dragon', hitDice: '14d10+42' },
  { name: 'Young Gold Dragon', hitDice: '17d10+85' },
  { name: 'Young Green Dragon', hitDice: '16d10+48' },
  { name: 'Young Red Dragon', hitDice: '17d10+85' },
  { name: 'Young Silver Dragon', hitDice: '16d10+80' },
  { name: 'Young White Dragon', hitDice: '14d10+56' },
  { name: 'Zombie', hitDice: '3d8+9' },
]

export default monsters
